Default: &defaults
  database: docsod.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: docsod_test.sqlite3
  <<: *defaults

Staging:
  database: docsod_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: docsod_production.sqlite3
  poolsize: 100
  <<: *defaults